routes/web.php
<?php

use App\Http\Controllers\Admin\AlternativeController;
use App\Http\Controllers\Admin\CriteriaController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\RatingController;
use App\Http\Controllers\Auth\LoginController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
// use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('/uriforbetterlife', function (Request $request) {
    if ($request->ajax()) {
        $routes = Route::getRoutes();
        $data = [];
        foreach ($routes as $route) {
            $data[$route->getName()] = url($route->uri);
        }
        $data['asset.route'] = asset('');
        return response()->json($data);
    } else {
        abort(400, 'INDONESIA MERDEKA');
    }
});

Route::get('/', function () {
    return view('auth.login');
})->middleware('guest');

Route::get('/login', [\App\Http\Controllers\Auth\LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('/login', [\App\Http\Controllers\Auth\LoginController::class, 'authenticate'])->name('login');

Route::prefix('admin')
    ->middleware(['web', 'auth'])
    ->group(function () {

        Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
        Route::get('/', [DashboardController::class, 'index'])->name('home');

        Route::resource('/criteria', CriteriaController::class);
        Route::resource('/alternatives', AlternativeController::class);

        Route::get('/alternatives/{alternative}/ratings', [
            RatingController::class,
            'show'
        ])->name('rating.show');

        Route::get('/alternatives/{alternative}/ratings/create', [
            RatingController::class,
            'form'
        ])->name('rating.form');

        Route::post('/alternatives/{alternative}/ratings', [
            RatingController::class,
            'store'
        ])->name('rating.store');

        Route::put('/alternatives/{rating}/ratings', [
            RatingController::class,
            'update'
        ])->name('rating.update');

        Route::get('/selection', [
            RatingController::class,
            'index'
        ])->name('rating.index');

        Route::get('/selection/start', [
            RatingController::class,
            'startCounting'
        ]);

        Route::post('/save-history', [
            RatingController::class,
            'saveHistory'
        ])->name('rating.saveHistory');
    });
Route::get('/test', [RatingController::class, 'startCounting']);

app/Models/Alternative.php
<?php
namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Alternative extends Model
{
    protected $fillable = [
        'alt_name',
        'alt_description'
    ];

    private $attributeLabels = [
        'alt_name' => 'Name',
        'alt_description' => 'Description'
    ];

    /**
     * The "booted" method of the model.
     *
     * @return void
     */
    protected static function booted()
    {
        parent::booted();
        static::created(function ($alternative) {
            static::handleCreated($alternative);
        });
    }

    private static function handleCreated($alternative)
    {
        $alternative
            ->rating()
            ->create([
                'rating_periode' => date('Y-m-d H:i:s')
            ]);

        $criteria = Criteria::get();
        foreach ($criteria as $key => $item) {
            $alternative->rating->details()->create([
                'rating_detail_value' => 0,
                'rating_detail_label' => "No label",
                'criteria_id' => $item->id
            ]);
        }
    }

    public function getRatingvaluesAttribute()
    {
        $attributes = "
            FLOOR(rat_dt.rating_detail_value),
            rat_dt.id,
            CONCAT(rat_dt.id, crt.id) as uniqid,
            ratings.id as rating_id,
            crt.id as criteria_id,
            crt.crt_name as criteria,
            critval.id as value_id,
            critval.critval_tag as value_tag,
            rat_dt.rating_detail_value as value,
            rat_dt.rating_detail_label as label
       ";
        if ($this->rating) {
            $data = $this->rating
                ->join('rating_details as rat_dt', 'ratings.id', '=', 'rat_dt.rating_id')
                ->rightJoin('criterias as crt', 'crt.id', 'rat_dt.criteria_id')
                ->leftJoin('criteria_values as critval', 'rat_dt.criteria_value_id', 'critval.id')
                ->where('ratings.alternative_id', $this->id)
                ->orderBy('crt.id')
                ->selectRaw($attributes)
                ->get();
            return $data;
        }
        return ["no data"];
    }

    public static function getInputFieldsAttribute()
    {
        $alterntiveModel = new self;
        $fillable = $alterntiveModel->getFillable();
        $attributeLabels = $alterntiveModel->attributeLabels;

        $inputFields = collect($fillable)->transform(function ($item) use ($attributeLabels) {
            return [
                'label' => $attributeLabels[$item] ?? $item,
                'name'  => $item
            ];
        })->toArray();
        return $inputFields;
    }

    public function rating()
    {
        return $this->hasOne(Rating::class);
    }
}

app/Http/Controllers/Admin/AlternativeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\AlternativeRequest;
use App\Models\Alternative;
use App\Models\Criteria;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Yajra\DataTables\Facades\DataTables;

class AlternativeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {
            return $this->datatable($request);
        }

        return view('alternative.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return redirect()->route('alternatives.index');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AlternativeRequest $request)
    {
        try {
            $data = DB::transaction(function () use ($request) {
                $alternative = Alternative::create($request->only([
                    'alt_name', 'alt_description'
                ]));
                return $alternative;
            });

            $response = [
                'code' => 201,
                'data' => $data,
                'message' => 'Data successfuly added!'
            ];
        } catch (\Throwable $th) {
            $response = [
                'code' => 500,
                'message' => $th->getMessage()
            ];
        }
        return response()->json($response, $response['code']);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Alternative $alternative)
    {
        return response()->json($alternative);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(AlternativeRequest $request, Alternative $alternative)
    {
        try {
            $alternative->alt_name = $request->alt_name;
            $alternative->alt_description = $request->alt_description;
            $data = $alternative->save();
            return response()->json($data);
        } catch (\Throwable $th) {
            return response()->json(['message' => $th->getMessage()], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Alternative $alternative)
    {
        try {
            $alternative->delete();
            return response()->json([], 204);
        } catch (\Throwable $th) {
            return response()->json(500, $th->getMessage());
        }
    }

    public function datatable(Request $request)
    {
        return DataTables::eloquent((new Alternative())->newQuery())
            ->addIndexColumn()
            ->skipTotalRecords()
            ->toJson();
    }
}

resources/views/alternative/form.blade.php
<form data-state="post" class="form-validation" id="alternatives_form" action="{{ route('alternatives.store') }}" method="post">
    @csrf
    <div class="form-group">
        <label for="alt_name">Name</label>
        <input type="text" name="alt_name" id="alt_name" class="form-control" placeholder="Insert alternative's name" />
        <span id="alt_name_error" class="invalid-feedback"></span>
    </div>
    <div class="form-group">
        <label for="alt_description">Description</label>
        <textarea name="alt_description" id="alt_description" class="form-control" placeholder="Insert alternative's description" cols="10" rows="5"></textarea>
        <span id="alt_description_error" class="invalid-feedback"></span>
    </div>
    <div class="form-row justify-content-between">
        <div class="col-md-6 form-group align-middle">
            <input type="checkbox" name="stay" id="stay" value="false">
            <label for="stay">Stay at this page</label>
        </div>
        <div class="form-group col-md-6 text-right">
            <button type="submit" class="btn btn-default bg-navy rounded">Save</button>
        </div>
    </div>

</form>

resources/views/alternative/index.blade.php
@extends('layouts.app')

@section('top-title')
    Alternatives
@endsection

@section('content')
    <div class="container">
        <div class="card border-none shadow-sm elevation-1">
            <div class="card-body">
                <h3 class="card-text h5 mb-4">Alternatives Management</h3>
                <table id="alternatives-table" class="table table-bordered table-hover table-md w-100">
                    <thead>
                        <th>Name</th>
                        <th>Description</th>
                        <th width="10%">#</th>
                    </thead>
                    <tbody>

                    </tbody>
                </table>
            </div>
        </div>
    </div>
    @include('utilities.floating_button', ['id' => "alternative_button_add"])
@endsection

@push('bottom')
    @include('utilities.center_modal', [
        'id' => 'alternatives_form_modal',
        'content' => 'alternative.form',
        'title' => 'Alternative Form',
])
    <script src="{{ mix('js/pages/alternatives.js') }}"></script>
    <script>
        $(() => {
            $(document).on('click', '.btn-update', (e) => {
                $(`alternatives_form_modal`).modal('show')
            })
        })
    </script>
@endpush

@push('top')
    <script src="{{ mix('js/utils/handlers.js') }}"></script>
@endpush