routes/web.php
<?php

use App\Http\Controllers\Admin\AlternativeController;
use App\Http\Controllers\Admin\CriteriaController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\RatingController;
use App\Http\Controllers\Auth\LoginController;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
// use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::post('/uriforbetterlife', function (Request $request) {
    if ($request->ajax()) {
        $routes = Route::getRoutes();
        $data = [];
        foreach ($routes as $route) {
            $data[$route->getName()] = url($route->uri);
        }
        $data['asset.route'] = asset('');
        return response()->json($data);
    } else {
        abort(400, 'INDONESIA MERDEKA');
    }
});

Route::get('/', function () {
    return view('auth.login');
})->middleware('guest');

Route::get('/login', [\App\Http\Controllers\Auth\LoginController::class, 'index'])->name('login')->middleware('guest');
Route::post('/login', [\App\Http\Controllers\Auth\LoginController::class, 'authenticate'])->name('login');

Route::prefix('admin')
    ->middleware(['web', 'auth'])
    ->group(function () {

        Route::post('/logout', [LoginController::class, 'logout'])->name('logout');
        Route::get('/', [DashboardController::class, 'index'])->name('home');

        Route::resource('/criteria', CriteriaController::class);
        Route::resource('/alternatives', AlternativeController::class);

        Route::get('/alternatives/{alternative}/ratings', [
            RatingController::class,
            'show'
        ])->name('rating.show');

        Route::get('/alternatives/{alternative}/ratings/create', [
            RatingController::class,
            'form'
        ])->name('rating.form');

        Route::post('/alternatives/{alternative}/ratings', [
            RatingController::class,
            'store'
        ])->name('rating.store');

        Route::put('/alternatives/{rating}/ratings', [
            RatingController::class,
            'update'
        ])->name('rating.update');

        Route::get('/selection', [
            RatingController::class,
            'index'
        ])->name('rating.index');

        Route::get('/selection/start', [
            RatingController::class,
            'startCounting'
        ]);

        Route::post('/save-history', [
            RatingController::class,
            'saveHistory'
        ])->name('rating.saveHistory');
    });
Route::get('/test', [RatingController::class, 'startCounting']);

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="base-url" content="{{ url('') }}">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    {{-- <link rel="shortcut icon" href="{{ asset('images/logo-sm.png') }}" type="image/x-icon"> --}}

    <title>@yield('top-title', config('app.name')) &mdash; {{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    {{-- <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet"> --}}
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

    <script src="https://kit.fontawesome.com/dbac1250c3.js" crossorigin="anonymous"></script>
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    @yield('javascript')
    @stack('top')
</head>

<body class="hold-transition layout-top-nav accent-navy text-sm">
    @include('utilities.notification')
    <div class="wrapper">

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand-md navbar-dark navbar-navy sticky-top shadow-sm">
            <div class="container">
                <a href="{{ route('home') }}" class="navbar-brand">
                    <span class="brand-text text-white font-weight-normal">{{ config('app.name') }}</span>
                </a>

                <a class="navbar-toggler order-1 text-sm border-0" data-toggle="collapse"
                    data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </a>

                <div class="collapse navbar-collapse order-3" id="navbarCollapse">
                    <!-- Left navbar links -->
                    @include('layouts.topnav')
                </div>

                <!-- Right navbar links -->
                <ul class="order-1 order-md-3 navbar-nav navbar-no-expand ml-auto d-none d-md-inline">

                    <!-- Profile Dropdown Menu -->
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle {{ !request()->is('myprofile*') ? "" : "active" }}" data-toggle="dropdown" href="#">
                            <i class="fas fa-user-circle"></i> {{ auth()->user()->name }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                            <span class="dropdown-header text-left">Hi, {{ auth()->user()->name }}</span>
                            <div class="dropdown-divider"></div>
                            {{-- <a href="{{ route('myprofile.index') }}" class="dropdown-item">
                                <i class="fas fa-user-cog mr-2"></i> Profile
                            </a> --}}
                            <div class="dropdown-divider"></div>
                            <form action="{{ route('logout') }}" method="post">
                                @csrf
                                <button type="submit" class="dropdown-item border-0 btn btn-link text-dark">
                                    <i class="fas fa-sign-out-alt mr-2"></i> Logout
                                </button>
                            </form>
                            <div class="dropdown-divider"></div>
                        </div>
                    </li>

                </ul>
            </div>
        </nav>
        <!-- /.navbar -->

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper py-3">
            <!-- Content Header (Page header) -->
            @yield('content-header')
            <!-- /.content-header -->

            <!-- Main content -->
            <div class="content">
                @yield('content')
            </div>
            <!-- /.content -->
        </div>
        <!-- Main Footer -->
        <footer class="main-footer">
            <!-- To the right -->
            <div class="float-right d-none d-sm-inline">
                V.1.0.0
            </div>
            <!-- Default to the left -->
            DSS
        </footer>
    </div>
    @stack('bottom')
</body>

</html>

resources/views/layouts/topnav.blade.php
<ul class="navbar-nav">
    <li class="nav-item {{ request()->is('admin') ? 'active' : '' }}">
        <a href="{{ route('home') }}" class="nav-link">Home</a>
    </li>
    <li class="nav-item {{ request()->is('admin/criteria*') ? 'active' : '' }}">
        <a href="{{ route('criteria.index') }}" class="nav-link">Criteria</a>
    </li>
    <li class="nav-item {{ request()->is('admin/alternatives*') ? 'active' : '' }}">
        <a href="{{ route('alternatives.index') }}" class="nav-link">Alternatives</a>
    </li>
    <li class="nav-item {{ request()->is('admin/selection*') ? 'active' : '' }}">
        <a href="{{ route('rating.index') }}" class="nav-link">Selection</a>
    </li>

    <li class="nav-item d-inline d-md-none ">
        <form action="{{ route('logout') }}" method="post">
            @csrf
            <button type="submit" class="dropdown-item nav-link border-0 btn btn-link">
                Logout
            </button>
        </form>
    </li>
</ul>